# Generated by Django 4.1.3 on 2022-11-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_teacherproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastt_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lastt_name',
            field=models.CharField(max_length=200),
        ),
    ]
