# Generated by Django 4.1.3 on 2022-11-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_student_lastt_name_alter_teacher_lastt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
