# Generated by Django 4.1.3 on 2022-11-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_teacher_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastt_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
