# Generated by Django 4.1.3 on 2022-12-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_examen_final_proyecto_student_born_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
